/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\BELAKANG.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Belakang(props) {
  const { nodes, materials } = useGLTF('/3dModel/.GLB/BELAKANG.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Belakang.geometry} material={nodes.Belakang.material} position={[-0.01, 1.38, -0.32]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/3dModel/.GLB/BELAKANG.glb')
