/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\DEPAN KANAN.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function DepanKanan(props) {
  const { nodes, materials } = useGLTF('/3dModel/.GLB/DEPAN KANAN.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Depan_Kanan.geometry} material={nodes.Depan_Kanan.material} position={[-0.35, 1.45, 0.4]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/3dModel/.GLB/DEPAN KANAN.glb')
