/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\KANCING.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Kancing(props) {
  const { nodes, materials } = useGLTF('/3dModel/.GLB/KANCING.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Kancing.geometry} material={nodes.Kancing.material} position={[0, 1.81, 0.5]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/3dModel/.GLB/KANCING.glb')
