/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\KEMEJA FIXED.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function KemejaFixed(props) {
  const { nodes, materials } = useGLTF('/3dModel/.GLB/KEMEJA FIXED.glb')
  const fabricTextureProps = useTexture({
    map: "/3dModel/.GLB/Textures/Fabric_035_SD/Batik1.png",
    // map: "/3dModel/.GLB/Textures/Fabric_035_SD/Fabric_035_basecolor.jpg",
    // normalMap: "/3dModel/.GLB/Textures/Fabric_035_SD/Fabric_035_normal.jpg",
    // roughnessMap: "/3dModel/.GLB/Textures/Fabric_035_SD/Fabric_035_roughness.jpg",
    aoMap: "/3dModel/.GLB/Textures/Fabric_035_SD/Fabric_035_ambientOcclusion.jpg",
  })


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Kancing.geometry} material={nodes.Kancing.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Depan_Kiri.geometry} material={nodes.Depan_Kiri.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Lengan_Kiri.geometry} material={nodes.Lengan_Kiri.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Belakang.geometry} material={nodes.Belakang.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Lengan_Kanan.geometry} material={nodes.Lengan_Kanan.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Kerah.geometry} material={nodes.Kerah.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Depan_Kanan.geometry} rotation={[Math.PI / 2, 0, 0]} >
        <meshStandardMaterial {...fabricTextureProps} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/3dModel/.GLB/KEMEJA FIXED.glb')
