/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\KERAH.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Kerah(props) {
  const { nodes, materials } = useGLTF('/3dModel/.GLB/KERAH.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Kera.geometry} material={nodes.Kera.material} position={[0, 2.77, 0.04]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/3dModel/.GLB/KERAH.glb')
