/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\LENGAN KIRI.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LenganKiri(props) {
  const { nodes, materials } = useGLTF('/3dModel/.GLB/LENGAN KIRI.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lengan_Kanan.geometry} material={nodes.Lengan_Kanan.material} position={[0.95, 1.88, -0.15]} rotation={[Math.PI / 2, 0, 0]} scale={1.01} />
    </group>
  )
}

useGLTF.preload('/3dModel/.GLB/LENGAN KIRI.glb')
