/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\LENGAN KANAN.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LenganKanan(props) {
  const { nodes, materials } = useGLTF('/3dModel/.GLB/LENGAN KANAN.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lengan_Kiri.geometry} material={nodes.Lengan_Kiri.material} position={[-0.97, 1.87, -0.15]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/3dModel/.GLB/LENGAN KANAN.glb')
